name: API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.22"

      - name: Download Go modules
        run: go mod download

      - name: Run API tests
        run: go test ./... -v

      - name: Collect Allure results
        if: always()
        run:  |
          mkdir -p allure-results
          find . -type d -name allure-results | while read dir; do
            if [ "$dir" != "./allure-results" ]; then
              cp -r "$dir/"* allure-results/ || true
            fi
          done

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results
          path: allure-results

publish-report:
  if: always()
  needs: [ run-tests ]
  runs-on: ubuntu-latest

  steps:
    - name: Check out repository
      uses: actions/checkout@v6
      with:
        ref: gh-pages
        path: gh-pages

    - name: Download Allure results
      uses: actions/download-artifact@v6
      with:
        name: allure-results
        path: allure-results

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.13
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
